services:
    php-apache-environment:
        container_name: php-apache
        hostname: localhost
        build:
            dockerfile: ./PasswordManagerDockerfile/Dockerfile
        links:
            - db
        volumes:
            - ./PasswordManagerVersions/9.08/src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: password_manager
            MYSQL_USER: mike
            MYSQL_PASSWORD: admin
        volumes:
            - ./PasswordManagerVersions/9.08/initial.sql:/docker-entrypoint-initdb.d/db.sql